<div class="row">
	<div class="col-sm">
		<h1>Albums</h1>
	</div>
</div>
<div class="row">
	<?php foreach($albums as $alb){?>
		<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
			<div class="card">
				<img src="/images/<?= $alb->imagen ?>"  height="250" width="auto" >
				<div class="card-body">
					<h5 class="card-title"><?= $alb->album_name ?></h5>
					<h5 class="card-title">Stamps: <?= $alb->num_stamps ?></h5>
					
				</div>
				
			</div>
		</div>
	<?php }?>
	
</div>