<div class="row">
	<div class="col-sm">
		<h1>Creating album</h1>

		<form action="submitalbum" method="post" enctype="multipart/form-data">
			<div class="form-group">
				<label for="album_img">Add album image</label>
				<input type="file" class="form-control-file" id="album_img" name="album_img">
			</div>
			<div class="form-group">
				<label for="title">Add album name title</label>
				<input type="text" class="form-control" id="title" name="title">
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
</div>