<style type="text/css">
	.thumbnail {
		width: 50px;
		height: 50px;
		border-radius: 25px;
	}
</style>

<div class="row">
	<div class="col-sm">
		<h1>List of stamps by year</h1>
		<a href="?p=list&v=table">View Table</a> | <a href="?p=list&v=icon">View Icons</a>
	</div>
</div>
<div class="row">
	<div class="col-sm">
		<table  id="myTable" class="table">
			<thead>
				<tr>
					<th>Year</th>
					<th>Stamp name</th>
					<th>Album</th>
					<th>Description</th>
					<th>Size</th>
					<th>Quantity</th>
					<th>Stamp in detail</th>
				</tr>
			</thead>
			<tbody>
				
				<tr>
					<td>1973</td>
					<td>Amalia de Sajonia</td>
					<td>Cuba</td>
					<td>Woman in a yellow dress</td>
					<td>253 x 356 mm</td>
					<td>1</td>
					<td><a href="stamp" style="text-align: center;">-></a></td>
				</tr>
				
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('#myTable').DataTable();
	});
</script>