<!doctype html>
<html lang="en">
<head>
	<title><?= $title ?></title>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<!-- dataTables -->
	<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

	<!--Import jQuery before export.js-->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>


   <!--Data Table-->
   <script type="text/javascript"  src=" https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
   <script type="text/javascript"  src=" https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>

   <!--Export table buttons-->
   <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
   <script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.24/build/pdfmake.min.js" ></script>
   <script type="text/javascript"  src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.24/build/vfs_fonts.js"></script>
   <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"></script>
   <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.1/js/buttons.print.min.js"></script>

	<!--Export table button CSS-->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css">

	<style type="text/css">
		.card {
			margin-bottom: 30px;
		}
		.card-img-top {
			height: 150px;
		}
	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="#">Stamps Collections</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse">
			<ul class="navbar-nav">
				
				<li class="nav-item ">
					<a class="nav-link" href="/albumlist">Albums</a>
				</li>
                <li class="nav-item ">
					<a class="nav-link" href="/newalbum">Create new album</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/newstamp">Add new stamp</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/reports/byyear">Stamps by year</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/reports/repeated">Repeated stamps</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/reports/unglued">Unglued stamps</a>
				</li>
                <li class="nav-item">
					<a class="nav-link" href="logout">Logout</a>
				</li>
				
			</ul>
		</div>
	</nav>
	<div class="container">

    <?= $this->getContent() ?>

    </body>
</html>